version: '3'

services:
  warehouse:
    image: postgres:latest
    container_name: warehouse
    environment:
      POSTGRES_USER: ${WAREHOUSE_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB}
    volumes:
      - ./containers/warehouse:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${WAREHOUSE_USER}" ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    networks:
      - sde_network

  apps:
    image: abhishek_app
    container_name: abhishek_app
    build:
      context: ./containers/loader/
    volumes:
      - ./:/opt/sde
    environment:
      API_KEY: ${API_KEY}
    networks:
      - sde_network

networks:
  sde_network:
    name: sde_network
